# Generated by Django 2.1.7 on 2019-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
